# from typing import Literal
from typing_extensions import Literal

RELAY = "relay"
SINGLE = "single"
DOUBLE = "double"
LONG = "long"
ONLINE = "online"
ON = "ON"
OFF = "OFF"
STATE = "state"
PAHO = "paho.mqtt.client"
ClickTypes = Literal[SINGLE, DOUBLE, LONG]
MQTT = "mqtt"
HOST = "host"
USERNAME = "username"
PASSWORD = "password"
TOPIC_PREFIX = "topic_prefix"
HA_DISCOVERY = "ha_discovery"
ENABLED = "enabled"
GPIO_INPUT = "gpio_input"
OUTPUT = "output"
PIN = "pin"
ID = "id"
KIND = "kind"
GPIO = "gpio"
ACTIONS = "actions"
ACTION = "action"
OUTPUT = "output"
